name: Performance Monitoring

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1' # Weekly on Monday at 6 AM

env:
  NODE_VERSION: '20'

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Build application
        run: npm run build:ci

      - name: Start application
        run: |
          npm start &
          echo "Waiting for server to start..."
          sleep 30
          curl -f http://localhost:3000 || exit 1

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            http://localhost:3000
            http://localhost:3000/about
            http://localhost:3000/contact
            http://localhost:3000/resources/training
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: './lighthouserc.json'

      - name: Comment performance results
        if: github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: `📊 **Performance Report**
                 
                 Lighthouse performance audit completed. Check the workflow artifacts for detailed results.
                 
                 **Key Metrics:**
                 - Performance Score: See Lighthouse report
                 - Accessibility Score: See Lighthouse report
                 - Best Practices Score: See Lighthouse report
                 - SEO Score: See Lighthouse report`
            });
